version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.2
    env_file:
      - .env
    ports:
      - "6379:6379"

  celery:
    build: .
    env_file:
      - .env
    command: ./celery_tasks/start_celery.sh
    depends_on:
      - redis
    volumes:
      - .:/app

  celery_beat:
    build: .
    command: ./celery_tasks/start_celery_beat.sh
    volumes:
      - .:/app
    depends_on:
      - redis

  flower:
    image: mher/flower:2.0.1
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  postgres_data:
  media_data: